# Generated by Django 5.0.4 on 2024-04-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(verbose_name='Event Date')),
            ],
        ),
        migrations.AlterModelOptions(
            name='trial',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='trial',
            name='date',
            field=models.DateField(verbose_name='Trial Date'),
        ),
        migrations.AddField(
            model_name='dog',
            name='events',
            field=models.ManyToManyField(to='main_app.event'),
        ),
    ]
